import datetime

a = [
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 11,
        "ModifyNote": None,
        "PartyName": "CHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 12,
        "ModifyNote": None,
        "PartyName": "CMI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 13,
        "ModifyNote": None,
        "PartyName": "DHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 14,
        "ModifyNote": None,
        "PartyName": "Edge",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 0.0793650794,
        "LBRawID": 15,
        "ModifyNote": None,
        "PartyName": "KDDI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.0634920635,
        "LBRawID": 16,
        "ModifyNote": None,
        "PartyName": "Singtel",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 17,
        "ModifyNote": None,
        "PartyName": "SKB",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 18,
        "ModifyNote": None,
        "PartyName": "Telin",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 19,
        "ModifyNote": None,
        "PartyName": "TRUE",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 20,
        "ModifyNote": None,
        "PartyName": "VNPT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 1,
        "ModifyNote": None,
        "PartyName": "CHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 2,
        "ModifyNote": None,
        "PartyName": "CMI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 3,
        "ModifyNote": None,
        "PartyName": "DHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 4,
        "ModifyNote": None,
        "PartyName": "Edge",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 0.0793650794,
        "LBRawID": 5,
        "ModifyNote": None,
        "PartyName": "KDDI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.0634920635,
        "LBRawID": 6,
        "ModifyNote": None,
        "PartyName": "Singtel",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 7,
        "ModifyNote": None,
        "PartyName": "SKB",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 8,
        "ModifyNote": None,
        "PartyName": "Telin",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 9,
        "ModifyNote": None,
        "PartyName": "TRUE",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 10,
        "ModifyNote": None,
        "PartyName": "VNPT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 1,
        "ModifyNote": None,
        "PartyName": "CHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 2,
        "ModifyNote": None,
        "PartyName": "CMI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 3,
        "ModifyNote": None,
        "PartyName": "DHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 4,
        "ModifyNote": None,
        "PartyName": "Edge",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 0.0793650794,
        "LBRawID": 5,
        "ModifyNote": None,
        "PartyName": "KDDI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.0634920635,
        "LBRawID": 6,
        "ModifyNote": None,
        "PartyName": "Singtel",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 7,
        "ModifyNote": None,
        "PartyName": "SKB",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 8,
        "ModifyNote": None,
        "PartyName": "Telin",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 9,
        "ModifyNote": None,
        "PartyName": "TRUE",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM9a",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 10,
        "ModifyNote": None,
        "PartyName": "VNPT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 11,
        "ModifyNote": None,
        "PartyName": "CHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 12,
        "ModifyNote": None,
        "PartyName": "CMI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 13,
        "ModifyNote": None,
        "PartyName": "DHT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 28.5714285714,
        "LBRawID": 14,
        "ModifyNote": None,
        "PartyName": "Edge",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 0.0793650794,
        "LBRawID": 15,
        "ModifyNote": None,
        "PartyName": "KDDI",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.0634920635,
        "LBRawID": 16,
        "ModifyNote": None,
        "PartyName": "Singtel",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 17,
        "ModifyNote": None,
        "PartyName": "SKB",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 3.5714285714,
        "LBRawID": 18,
        "ModifyNote": None,
        "PartyName": "Telin",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 19,
        "ModifyNote": None,
        "PartyName": "TRUE",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
    {
        "BillMilestone": "BM12",
        "CreateDate": datetime.datetime(2022, 12, 27, 14, 30),
        "EndDate": None,
        "LBRatio": 7.1428571429,
        "LBRawID": 20,
        "ModifyNote": None,
        "PartyName": "VNPT",
        "SubmarineCable": "SJC2",
        "WorkTitle": "Construction",
    },
]

print(len(a))
print(list(set(a)))
